name: Generate Animated Hero (pacman-run)

on:
  schedule:
    - cron: '0 1 * * *'   # 01:00 UTC daily (staggered from snake.yml)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  regenerate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate svgs again (snake + pacman + hero)
        run: |
          mkdir -p output
          python3 .github/workflows/generator.py || true

      - name: Commit updated svgs
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: refresh pacman + hero svgs"
          add: "output/*.svg"
