name: GitHub Pacman


on:
schedule:
- cron: '0 0 * * *' # runs daily at midnight UTC — change if needed
workflow_dispatch: {}


jobs:
generate-pacman:
runs-on: ubuntu-latest


steps:
- uses: actions/checkout@v4


- name: Generate pacman.svg
run: |
python3 - <<'PY' > pacman.svg
import math


w, h = 800, 160
pac_x, pac_y, pac_r = 80, 80, 60
mouth_angle = math.radians(40)


def circle(cx, cy, r, fill):
return f'<circle cx="{cx}" cy="{cy}" r="{r}" fill="{fill}" />
'


def polygon(points, fill):
pts = ' '.join(f'{x},{y}' for x,y in points)
return f'<polygon points="{pts}" fill="{fill}" />
'


# Pac-Man body (full circle) then mouth overlay to cut
svg = []
svg.append(f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="0 0 {w} {h}">')
svg.append('<rect width="100%" height="100%" fill="#071017"/>')


# Pac-Man (yellow circle)
svg.append(circle(pac_x, pac_y, pac_r, '#FFD300'))


# Mouth: overlay a triangle shaped polygon matching background to "cut" the mouth
angle1 = -mouth_angle/2
angle2 = mouth_angle/2
p1 = (pac_x, pac_y)
p2 = (pac_x + pac_r * math.cos(angle1), pac_y + pac_r * math.sin(angle1))
p3 = (pac_x + pac_r * math.cos(angle2), pac_y + pac_r * math.sin(angle2))
svg.append(polygon([p1,p2,p3], '#071017'))


# Eye
svg.append(circle(pac_x + 20, pac_y - 20, 6, '#111'))


# Dots
dot_x = pac_x + pac_r + 20
for i in range(10):
svg.append(circle(dot_x + i*60, pac_y, 10, '#ffffff'))


svg.append('</svg>')


print('
'.join(svg))
PY


- name: Commit generated pacman
run: |
git config user.name "github-actions[bot]"
git config user.email "github-actions[bot]@users.noreply.github.com"
git add pacman.svg || true
git commit -m "chore: update pacman.svg" || echo "No changes to commit"
git push || echo "Push failed — check permissions"
