name: GitHub Snake


on:
schedule:
- cron: '0 0 * * *' # runs daily at midnight UTC — change if needed
workflow_dispatch: {}


jobs:
generate-snake:
runs-on: ubuntu-latest


steps:
- uses: actions/checkout@v4


- name: Generate snake.svg with Platane SNK
uses: platane/snk@v4
with:
background: '10,10,10' # RGB or hex without '#'
color: '0,200,120' # snake color
output: 'snake.svg'


- name: Commit generated snake
run: |
git config user.name "github-actions[bot]"
git config user.email "github-actions[bot]@users.noreply.github.com"
git add snake.svg || true
git commit -m "chore: update snake" || echo "No changes to commit"
git push || echo "Push failed — check permissions"
