name: Generate Snake + Pac-Man Hero

on:
  schedule:
    - cron: "0 0 * * *"  # run daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: SysQall
          outputs: |
            output/snake.svg
            output/snake-dark.svg?palette=github-dark

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Generate Pac-Man + Hero
        run: |
          mkdir -p output
          cat << 'EOF' > output/pacman.svg
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 40">
            <circle cx="20" cy="20" r="18" fill="yellow"/>
            <polygon points="20,20 38,10 38,30" fill="black"/>
            <circle cx="60" cy="20" r="4" fill="white"/>
            <circle cx="75" cy="20" r="4" fill="white"/>
            <circle cx="90" cy="20" r="4" fill="white"/>
          </svg>
          EOF

          cat << 'EOF' > output/hero.svg
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 120">
            <text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle"
                  font-size="28" font-family="monospace" fill="white">
              Thiago Tomaz — Backend Apprentice ⚡
            </text>
          </svg>
          EOF

      - name: Commit generated files
        uses: EndBug/add-and-commit@v9
        with:
          add: "output/*"
          message: "chore: update snake + pacman + hero svgs"
